name: diceware-auto
version: '1.0'
# synopsis:
# description:
license: ISC
author: Dino Morelli
maintainer: dino@ui3.info
copyright: 2019 Dino Morelli
category: Unclassified
extra-source-files:
- .gitignore
- package.yaml
- README.md
- stack.yaml

github: dino-/diceware-auto

ghc-options:
- -fwarn-tabs
- -Wall
- -Wcompat
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wredundant-constraints

dependencies:
- base >=3 && <5

library:
  source-dirs: src/lib
  dependencies:
  - bytestring
  - containers
  - cryptonite
  - filepath
  - text

executables:
  diceware-auto:
    source-dirs: src/diceware-auto
    main: Main.hs
    dependencies:
    - ansi-wl-pprint
    - diceware-auto
    - filepath
    - heredoc
    - optparse-applicative

# tests:
#   diceware-test-suite:
#     source-dirs: src/test
#     main: Main.hs
#     dependencies:
#     - diceware-auto
#     - tasty
#     - tasty-hspec
#     ghc-options:
#     - -rtsopts
#     - -threaded
#     - -with-rtsopts=-N
